import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/autoplay";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "bootstrap/dist/css/bootstrap.min.css";
import "@assets/css/odometer.min.css";
import "@assets/icon/icomoon/style.css";
import "@assets/css/animate.css";
import "@assets/scss/app.scss";
import localFont from "next/font/local";

const mono = localFont({
  src: "../fonts/DepartureMono-Regular.otf",
  display: "swap",
  variable: "--font-mono",
});

const geist = localFont({
  src: [
    { path: "../fonts/Geist-Regular.ttf", weight: "400", style: "normal" },
    { path: "../fonts/Geist-Medium.ttf", weight: "500", style: "normal" },
    { path: "../fonts/Geist-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-geist",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Qore - Next Js AI Template",
  description:
    "Qore is an AI-powered Next.js template generated by Themesflat, optimized for high performance and modern design.",
  keywords: [
    "Qore",
    "Next.js",
    "AI Template",
    "Themesflat",
    "React",
    "Website Template",
  ],
  robots: "index, follow",
  authors: [{ name: "Themesflat", url: "https://themesflat.co" }],
  icons: {
    icon: "/assets/images/logo/logo.png",
    shortcut: "/assets/images/logo/logo.png",
    apple: "/assets/images/logo/logo.png",
  },
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="mn"
      className={`${geist.className} ${geist.variable} ${mono.variable}`}
    >
      <head></head>
      <body>{children}</body>
    </html>
  );
}
